language: php
php:
  - nightly
install: composer install
env:
  - TRAVIS=1
before_script:
  - vendor/bin/propel --config-dir="$(pwd)/tests" config:convert
  - vendor/bin/propel --config-dir="$(pwd)/tests" model:build
  - vendor/bin/propel --config-dir="$(pwd)/tests" migration:diff
  - vendor/bin/propel --config-dir="$(pwd)/tests" migration:migrate
  - rm -rf "$(pwd)/tests/Propel/Migration"
script: phpunit -c phpunit.xml